-- CREATE CTD_VARIABLE_CODES

CREATE TABLE VARIABLE_CODES (
  VARIABLE    NUMBER(3,0) NOT NULL,
  NAME        VARCHAR2(255 BYTE),
  UNITS       VARCHAR2(255 BYTE),
  DESCRIPTION VARCHAR2(255 BYTE),
  
  CONSTRAINT pk_variable_codes
    PRIMARY KEY (VARIABLE)  
);
GRANT SELECT ON VARIABLE_CODES TO PUBLIC;


CREATE TABLE DIRECTION_CODES (
  DIRECTION   NUMBER(1,0) NOT NULL,
  DESCRIPTION VARCHAR2(255 BYTE),
  
  CONSTRAINT pk_direction_codes
    PRIMARY KEY (DIRECTION)
);
GRANT SELECT ON DIRECTION_CODES TO PUBLIC;

CREATE TABLE INSTRUMENT_CODES (
  INSTRUMENT  NUMBER(3,0) NOT NULL,
  DESCRIPTION VARCHAR2(255 BYTE),
  
  CONSTRAINT pk_instrument_codes 
    PRIMARY KEY (INSTRUMENT)
);
GRANT SELECT ON INSTRUMENT_CODES TO PUBLIC;

-- CREATE TABLE CTD_HAUL_INSTRUMENT (
--   HAULJOIN   NUMBER(12,0) NOT NULL, 
--   INSTRUMENT NUMBER(3,0)  NOT NULL,
--   
--   --CONSTRAINT fk_ctd_haul_instrument_hauljoin 
--    --FOREIGN KEY (HAULJOIN) REFERENCES RACEBASE.HAUL(HAULJOIN),
--     
--   CONSTRAINT fk_ctd_haul_instrument_instrument 
--     FOREIGN KEY (INSTRUMENT) REFERENCES CTD_INSTRUMENT_CODES(INSTRUMENT)
-- );
-- GRANT SELECT ON CTD_HAUL_INSTRUMENT TO PUBLIC;

CREATE TABLE ENVIRONMENTAL (
  HAULJOIN   NUMBER(12,0)  NOT NULL, 
  INSTRUMENT NUMBER(3,0)   NOT NULL,
  DIRECTION  NUMBER(12,0)  NOT NULL,
  DEPTH_M    NUMBER(5,0)   NOT NULL,
  VARIABLE   NUMBER(3,0)   NOT NULL,
  VALUE      NUMBER(11,6)  NOT NULL, 
  
  -- Foreign Key Constraints
  --CONSTRAINT fk_env_hauljoin 
    --FOREIGN KEY (HAULJOIN) REFERENCES RACEBASE.HAUL(HAULJOIN), 
    
    CONSTRAINT fk_env_instrument 
    FOREIGN KEY (INSTRUMENT) REFERENCES INSTRUMENT_CODES(INSTRUMENT),
    
  CONSTRAINT fk_env_direction 
    FOREIGN KEY (DIRECTION) REFERENCES DIRECTION_CODES(DIRECTION),
    
  CONSTRAINT fk_env_variable 
    FOREIGN KEY (VARIABLE) REFERENCES VARIABLE_CODES(VARIABLE),
    
  -- Composite Primary Key Constraint
  CONSTRAINT pk_env_data 
    PRIMARY KEY (HAULJOIN, DIRECTION, DEPTH_M, VARIABLE)
);
GRANT SELECT ON ENVIRONMENTAL TO PUBLIC;







