---
title: "crab_compare"
output: html_document
date: "2026-05-10"
---

# Pull tables

```{r data_dl}

files <-  c("crab_sizecomp", "crab_biomass", "crab_cpue", 
            # "crabpack_specimen", "crab_specimen",
            "crab_sizecomp_pack", "crab_biomass_pack", "crab_cpue_pack")
for (filesi in files) {
temp <- read.csv(file = here::here(paste0("data/", filesi, ".csv"))) |> 
  dplyr::rename_all(tolower)
assign(x = filesi, temp)
}

gapindex_sizecomp <- crab_sizecomp
gapindex_biomass <- crab_biomass
gapindex_cpue <- crab_cpue |> 
  dplyr::mutate(area_swept_km2 = round(x = area_swept_km2, digits = 4))
crabpack_sizecomp <- crab_sizecomp_pack
crabpack_biomass <- crab_biomass_pack
crabpack_cpue <- crab_cpue_pack |> 
  dplyr::mutate(area_swept_km2 = round(x = area_swept_km2, digits = 4)) 
  # dplyr::mutate(area_swept_km2 = round(x = area_swept*3.4299, digits = 4)) #nmi2 to km2?

```


## Catch per unit effort

```{r compare-cpue}
cpue_compare <- dplyr::full_join(
  gapindex_cpue, 
  crabpack_cpue, 
  by = c("hauljoin", "species_code")) 

cpue_compare_diff <- cpue_compare |> 
  dplyr::mutate(
     weight_kg_diff = weight_kg.x - weight_kg.y,
                count_diff = count.x - count.y, 
                area_swept_km2_diff = area_swept_km2.x - area_swept_km2.y,
                count_diff = count.x - count.y, 
                cpue_kgkm2_diff = cpue_kgkm2.x - cpue_kgkm2.y, 
                cpue_nokm2_diff = cpue_nokm2.x - cpue_nokm2.y) |> 
  dplyr::select(hauljoin, species_code, dplyr::ends_with("_diff")) |> 
  dplyr::mutate(dplyr::across(dplyr::ends_with("_diff"), ~ ifelse(.x > 0.001, 1, 0)), 
                noteable_diff = (#weight_kg_diff  + area_swept_km2_diff + 
                                   count_diff + cpue_kgkm2_diff + cpue_nokm2_diff)) |> 
  dplyr::filter(noteable_diff > 0)

# cpue_compare_diff

a <- cpue_compare_diff |>
  dplyr::summarize(
    weight_kg_diff = sum(weight_kg_diff, na.rm = TRUE),
    count_diff = sum(count_diff, na.rm = TRUE),
    area_swept_km2_diff = sum(area_swept_km2_diff, na.rm = TRUE),
    cpue_kgkm2_diff = sum(cpue_kgkm2_diff, na.rm = TRUE),
    cpue_nokm2_diff = sum(cpue_nokm2_diff, na.rm = TRUE)
)

cpue_compare_diff_data <- cpue_compare |> 
  dplyr::right_join(cpue_compare_diff |> 
                      dplyr::select(hauljoin, species_code, noteable_diff))

print(paste0("Of ", nrow(cpue_compare), " records ( gapindex: ",nrow(gapindex_cpue), ", crabpack ", nrow(crabpack_cpue), "), ", nrow(cpue_compare_diff_data), " did not match. These issues occured in: ", paste0(names(a), ": ", a, collapse = ", ")))
# cpue_compare_diff_data
summary(cpue_compare_diff_data)

table(cpue_compare_diff_data$hauljoin, cpue_compare_diff_data$species_code)
write.csv(x = cpue_compare_diff_data, file = here::here("data/cpue_compare_diff_data.csv"))

```


```{r}
if (file.exists("Z:/Projects/ConnectToOracle.R")) {
  # This has a specific username and password because I DONT want people to have access to this!
  source("Z:/Projects/ConnectToOracle.R")
} else {
  # For those without a ConnectToOracle file
  library(rstudioapi)
  library(RODBC)
  channel <- odbcConnect(dsn = "AFSC", 
                         uid = rstudioapi::showPrompt(title = "Username", 
                                                      message = "Oracle Username", default = ""), 
                         pwd = rstudioapi::askForPassword("Enter Password"),
                         believeNRows = FALSE)
}

haul <- RODBC::sqlQuery(channel, paste0("SELECT * FROM GAP_PRODUCTS.HAUL; ")) |> 
  dplyr::rename_all(tolower)
cruise <- RODBC::sqlQuery(channel, paste0("SELECT * FROM GAP_PRODUCTS.CRUISE; ")) |> 
  dplyr::rename_all(tolower)

a <- cpue_compare_diff_data |>
  dplyr::left_join(haul) |> 
  dplyr::left_join(cruise) |> 
    dplyr::select(hauljoin, species_code, area_swept_km2.x, area_swept_km2.y, survey_name, survey_definition_id, vessel_name, year)
print("frequency in differences between cpue output") 
table(a$species_code, a$year, a$survey_name)

# how many numbers there should be

b <- cpue_compare |>
  dplyr::filter(weight_kg.x > 0 & weight_kg.y > 0) |> 
  dplyr::left_join(haul) |> 
  dplyr::left_join(cruise) |> 
    dplyr::select(hauljoin, species_code, survey_name, survey_definition_id, vessel_name, year) # |> 
  # dplyr::filter(species_code == 68560) 
print("all non-zero observations of cpue output") 
table(b$species_code, b$year, b$survey_name)

```


## Biomass

```{r compare-biomass-abundance}
gapindex_biomass <- gapindex_biomass |> 
    dplyr::filter(area_id %in% c(99900, #99901, 
                                 99902))
biomass_compare <- dplyr::full_join(
  gapindex_biomass |> 
    dplyr::select(species_code, year, survey_definition_id,
                  biomass_mt, population_count),
  crabpack_biomass  |> 
    dplyr::select(species_code, year, survey_definition_id, 
                  biomass_mt, population_count), 
  by = c("survey_definition_id", "year", "species_code"))

biomass_compare_diff <- biomass_compare |> 
  dplyr::mutate(biomass_mt_diff = biomass_mt.x - biomass_mt.y, 
                population_count_diff = population_count.x - population_count.y) |> 
  dplyr::select(survey_definition_id, year, species_code, 
                dplyr::ends_with("_diff")) |> 
  dplyr::mutate(dplyr::across(dplyr::ends_with("_diff"), ~ ifelse(.x > 0.01, 1, 0)), 
                noteable_diff = (biomass_mt_diff + population_count_diff)) |> 
  dplyr::filter(noteable_diff > 0)

# biomass_compare_diff

biomass_compare_diff_data <- biomass_compare |> 
  dplyr::right_join(biomass_compare_diff |> 
                      dplyr::select(survey_definition_id, year, species_code, noteable_diff))

a <- biomass_compare_diff |>
  dplyr::summarize(
    biomass_mt_diff = sum(biomass_mt_diff, na.rm = TRUE),
    population_count_diff = sum(population_count_diff, na.rm = TRUE)
)

print(paste0("Of ", nrow(biomass_compare), 
             " records ( gapindex: ",nrow(gapindex_biomass), 
             ", crabpack ", nrow(crabpack_biomass), "), ", nrow(biomass_compare_diff_data), 
             " did not match. These issues occured in: ", 
             paste0(names(a), ": ", a, collapse = ", ")))
# biomass_compare_diff_data
summary(biomass_compare_diff_data)

table(biomass_compare_diff_data$species_code, biomass_compare_diff_data$year, biomass_compare_diff_data$survey_definition_id)
write.csv(x = biomass_compare_diff_data, file = here::here("data/biomass_compare_diff_data.csv"))

```

## Sizecomp

```{r compare-sizecomp}

gapindex_sizecomp <- gapindex_sizecomp |> 
    dplyr::filter(area_id %in% c(99900, 99902)) |> 
    dplyr::select(-area_id) |>
    dplyr::filter(!is.na(population_count)) |>
    dplyr::filter(population_count != 0)
  crabpack_sizecomp <- crabpack_sizecomp |> 
    dplyr::filter(population_count != 0) |> 
    dplyr::filter(!is.na(population_count))

sizecomp_compare <- dplyr::full_join(
  gapindex_sizecomp, 
  crabpack_sizecomp, 
    # dplyr::mutate(population_count = ifelse(is.na(population_count), 0, population_count)) |>
  by = c("survey_definition_id", "year", "species_code", "length_mm", "sex"))


sizecomp_compare_diff <- sizecomp_compare |> 
  dplyr::mutate(population_count_diff = (population_count.x - population_count.y)) |> 
  dplyr::mutate(percent_diff = (population_count.y - population_count.x)/population_count.x) |>
  dplyr::mutate(dplyr::across(dplyr::ends_with("_diff"), ~ ifelse(.x > 0.000001, 1, 0)), 
                noteable_diff = (population_count_diff)) |> 
  dplyr::filter(noteable_diff > 0)

a <- sizecomp_compare_diff |>
  dplyr::summarize(
    population_count_diff = sum(population_count_diff, na.rm = TRUE)
)

print(paste0("Of ", nrow(sizecomp_compare), 
             " records ( gapindex: ",nrow(gapindex_sizecomp), 
             ", crabpack ", nrow(crabpack_sizecomp), "), ", nrow(sizecomp_compare_diff), 
             " did not match. These issues occured in: ", 
             paste0(names(a), ": ", a, collapse = ", ")))
# sizecomp_compare_diff
summary(sizecomp_compare_diff)
sizecomp_compare_diff_data <- sizecomp_compare |>
  dplyr::right_join(sizecomp_compare_diff |>
                      dplyr::select(survey_definition_id, year, species_code, noteable_diff))
# 
# sizecomp_compare_diff_data
# 
table(sizecomp_compare_diff_data$species_code, sizecomp_compare_diff_data$year, sizecomp_compare_diff_data$survey_definition_id)

write.csv(x = sizecomp_compare_diff_data, file = here::here("data/sizecomp_compare_diff_data.csv"))

```

