--------------------------------------------------------
--   Set up primary constraints for GAP_PRODUCTS tables
--------------------------------------------------------

-- Set up GAP_PRODUCTS.CPUE constraint
ALTER TABLE GAP_PRODUCTS.CPUE 
ADD CONSTRAINT CPUE_CONTRAINT 
PRIMARY KEY (HAULJOIN, SPECIES_CODE);

-- Set up GAP_PRODUCTS.BIOMASS constraint
ALTER TABLE GAP_PRODUCTS.BIOMASS
ADD CONSTRAINT BIOMASS_CONTRAINT 
PRIMARY KEY (SURVEY_DEFINITION_ID, YEAR, AREA_ID, SPECIES_CODE);

-- Set up GAP_PRODUCTS.SIZECOMP constraints
ALTER TABLE GAP_PRODUCTS.SIZECOMP
ADD CONSTRAINT SIZECOMP_CONTRAINT 
PRIMARY KEY (SURVEY_DEFINITION_ID, YEAR, AREA_ID, 
                SPECIES_CODE, SEX, LENGTH_MM);

-- Set up GAP_PRODUCTS.AGECOMP constraint
ALTER TABLE GAP_PRODUCTS.AGECOMP
ADD CONSTRAINT AGECOMP_CONTRAINT 
PRIMARY KEY (SURVEY_DEFINITION_ID, AREA_ID_FOOTPRINT, 
YEAR, AREA_ID, SPECIES_CODE, SEX, AGE);

--Set up primary key for AREA table
ALTER TABLE GAP_PRODUCTS.AREA 
ADD CONSTRAINT AREA_CONTRAINT 
PRIMARY KEY (SURVEY_DEFINITION_ID, DESIGN_YEAR, AREA_ID); 

--Set up primary key for STRATUM_GROUPS table
ALTER TABLE GAP_PRODUCTS.STRATUM_GROUPS
ADD CONSTRAINT STRATUM_GROUPS_CONTRAINT
PRIMARY KEY (SURVEY_DEFINITION_ID, DESIGN_YEAR, AREA_ID, STRATUM);

-- Set up primary key for SURVEY_DESIGN table
ALTER TABLE SURVEY_DESIGN
ADD CONSTRAINT SURVEY_DESIGN_CONTRAINT
PRIMARY KEY (SURVEY_DEFINITION_ID, YEAR);

-- Set up stratum groups constraints
ALTER TABLE GAP_PRODUCTS.STRATUM_GROUPS
ADD CONSTRAINT STRATUM_GROUPS_CONTRAINT
PRIMARY KEY (SURVEY_DEFINITION_ID, DESIGN_YEAR, AREA_ID, STRATUM);

-- Set up GAP_PRODUCTS.SPECIES_YEAR constraints
ALTER TABLE SPECIES_YEAR
ADD CONSTRAINT SPECIES_YEAR_CONTRAINT
PRIMARY KEY (SPECIES_CODE, YEAR_STARTED);

-- Set up GAP_PRODUCTS.METADATA_COLUMN constraints
ALTER TABLE METADATA_COLUMN
ADD CONSTRAINT METADATA_COLUMN_CONTRAINT
PRIMARY KEY (METADATA_COLNAME);
