-- SQL Command to Create Materialized View GAP_PRODUCTS.CRUISE
--
-- Note: the five survey areas w/ survey_definition_id:
-- "AI" = 52, "GOA" = 47, "EBS" = 98, "BSS" = 78, "NBS" = 143
--
-- Contributors: Ned Laman (ned.laman@noaa.gov), 
--               Zack Oyafuso (zack.oyafuso@noaa.gov), 
--               Emily Markowitz (emily.markowitz@noaa.gov)
--

CREATE MATERIALIZED VIEW GAP_PRODUCTS.CRUISE AS

SELECT 
    CRUISES.RACEBASE_CRUISEJOIN    AS CRUISEJOIN,
    CRUISES.CRUISE,
    SURVEYS.YEAR,
    SURVEYS.SURVEY_DEFINITION_ID,
    SDIS.SURVEY_NAME,
    CRUISES.VESSEL_ID,
    VESSELS.NAME                   AS VESSEL_NAME,
    ORGS.ACRONYM                   AS SPONSOR_ACRONYM,
    SURVEYS.START_DATE             AS DATE_START, 
    SURVEYS.END_DATE               AS DATE_END
FROM RACE_DATA.CRUISES CRUISES
JOIN RACE_DATA.SURVEYS SURVEYS 
    ON SURVEYS.SURVEY_ID = CRUISES.SURVEY_ID
JOIN RACE_DATA.SURVEY_DEFINITIONS SDIS 
    ON SDIS.SURVEY_DEFINITION_ID = SURVEYS.SURVEY_DEFINITION_ID
JOIN RACE_DATA.VESSELS VESSELS 
    ON VESSELS.VESSEL_ID = CRUISES.VESSEL_ID
JOIN RACE_DATA.ORGANIZATIONS ORGS 
    ON ORGS.ORGANIZATION_ID = SURVEYS.SPONSOR_ORGANIZATION_ID
JOIN (
    SELECT DISTINCT 
        CRUISEJOIN 
    FROM RACEBASE.HAUL 
    WHERE ABUNDANCE_HAUL = 'Y'
) HAUL 
    ON HAUL.CRUISEJOIN = CRUISES.RACEBASE_CRUISEJOIN
WHERE 
    SDIS.SURVEY_DEFINITION_ID IN (143, 98, 47, 52, 78);
    