CREATE OR REPLACE MATERIALIZED VIEW GAP_PRODUCTS.SPECIMEN_COUNT AS
WITH LENGTHS_SAMPLED AS (
    SELECT 
        SD.SURVEY_DEFINITION_ID,
        ABS(B.HAUL_ID) AS HAULJOIN, 
        CASE 
            WHEN C.SPECIES_CODE = 21721 THEN 21720 
            WHEN C.SPECIES_CODE = 21741 THEN 21740 
            ELSE C.SPECIES_CODE 
        END AS SPECIES_CODE,
        C.FREQUENCY
    FROM RACE_DATA.CRUISES A
    JOIN RACE_DATA.SURVEYS S ON (S.SURVEY_ID = A.SURVEY_ID)
    JOIN RACE_DATA.SURVEY_DEFINITIONS SD ON (SD.SURVEY_DEFINITION_ID = S.SURVEY_DEFINITION_ID)
    JOIN RACE_DATA.HAULS B ON (B.CRUISE_ID = A.CRUISE_ID)
    JOIN RACE_DATA.LENGTHS C ON (C.HAUL_ID = B.HAUL_ID)
)
/* 1. LENGTH DATA */
SELECT 
    CAST(BIO.SURVEY_DEFINITION_ID AS NUMBER(38,0)) AS SURVEY_DEFINITION_ID, 
    CAST(BIO.YEAR AS NUMBER(10,0)) AS YEAR, 
    CAST(L.SPECIES_CODE AS NUMBER(38,0)) AS SPECIES_CODE, 
    CAST('LENGTH' AS VARCHAR2(20)) AS SPECIMEN_SAMPLE_TYPE, 
    CAST(BIO.N_LENGTH AS NUMBER(38,0)) AS N_HAUL, 
    CAST(SUM(L.FREQUENCY) AS NUMBER(38,0)) AS N_SPECIMENS
FROM LENGTHS_SAMPLED L
JOIN HAUL H ON (L.HAULJOIN = ABS(H.HAULJOIN))
JOIN CRUISE C ON (H.CRUISEJOIN = C.CRUISEJOIN)
JOIN GAP_PRODUCTS.BIOMASS BIO 
    ON (L.SURVEY_DEFINITION_ID = BIO.SURVEY_DEFINITION_ID 
        AND C.YEAR = BIO.YEAR 
        AND L.SPECIES_CODE = BIO.SPECIES_CODE)
WHERE BIO.N_LENGTH > 0  
  AND BIO.AREA_ID IN (99900, 99902, 99903, 99904, 99905)
GROUP BY BIO.SURVEY_DEFINITION_ID, BIO.YEAR, L.SPECIES_CODE, BIO.N_LENGTH

UNION ALL

/* 2. OTOLITHS COLLECTED */
SELECT 
    CAST(C.SURVEY_DEFINITION_ID AS NUMBER(38,0)), 
    CAST(C.YEAR AS NUMBER(10,0)), 
    CAST(S.SPECIES_CODE AS NUMBER(38,0)),
    CAST('OTOLITHS' AS VARCHAR2(20)), 
    CAST(COUNT(DISTINCT S.HAULJOIN) AS NUMBER(38,0)),
    CAST(COUNT(*) AS NUMBER(38,0))
FROM SPECIMEN S
JOIN HAUL H ON S.HAULJOIN = H.HAULJOIN
JOIN CRUISE C ON (H.CRUISEJOIN = C.CRUISEJOIN)
GROUP BY C.SURVEY_DEFINITION_ID, C.YEAR, S.SPECIES_CODE

UNION ALL

/* 3. AGES COLLECTED */
SELECT 
    CAST(C.SURVEY_DEFINITION_ID AS NUMBER(38,0)), 
    CAST(C.YEAR AS NUMBER(10,0)), 
    CAST(S.SPECIES_CODE AS NUMBER(38,0)),
    CAST('AGE' AS VARCHAR2(20)), 
    CAST(COUNT(DISTINCT S.HAULJOIN) AS NUMBER(38,0)),
    CAST(COUNT(*) AS NUMBER(38,0))
FROM SPECIMEN S
JOIN HAUL H ON S.HAULJOIN = H.HAULJOIN
JOIN CRUISE C ON (H.CRUISEJOIN = C.CRUISEJOIN)
WHERE S.AGE IS NOT NULL
GROUP BY C.SURVEY_DEFINITION_ID, C.YEAR, S.SPECIES_CODE;

GRANT SELECT ON SPECIMEN_COUNT TO PUBLIC;