DROP MATERIALIZED VIEW SPECIMEN_COUNT;

CREATE MATERIALIZED VIEW SPECIMEN_COUNT AS

/* 1. LENGTHS COLLECTED */ 
WITH LENGTHS_SAMPLED AS (
    SELECT 
        SD.SURVEY_DEFINITION_ID,
        S.YEAR,
        C.HAUL_ID AS HAULJOIN, 
        CASE 
            WHEN C.SPECIES_CODE = 21721 THEN 21720 
            WHEN C.SPECIES_CODE = 21741 THEN 21740 
            ELSE C.SPECIES_CODE 
        END AS SPECIES_CODE
    FROM RACE_DATA.CRUISES A
    JOIN RACE_DATA.SURVEYS S ON (S.SURVEY_ID = A.SURVEY_ID)
    JOIN RACE_DATA.SURVEY_DEFINITIONS SD ON (SD.SURVEY_DEFINITION_ID = S.SURVEY_DEFINITION_ID)
    JOIN RACE_DATA.HAULS B ON (B.CRUISE_ID = A.CRUISE_ID)
    JOIN RACE_DATA.LENGTHS C ON (C.HAUL_ID = B.HAUL_ID)
    JOIN RACEBASE.HAUL RBH ON RBH.HAULJOIN = -B.HAUL_ID
    
    WHERE RBH.ABUNDANCE_HAUL = 'Y'
)
/* 1. LENGTH DATA */
SELECT 
    L.SURVEY_DEFINITION_ID, 
    L.YEAR, 
    L.SPECIES_CODE, 
    'LENGTH' AS SPECIMEN_SAMPLE_TYPE,   
    COUNT(DISTINCT(L.HAULJOIN)) AS N_HAUL, 
    COUNT(*) AS N_SPECIMEN
FROM LENGTHS_SAMPLED L
GROUP BY L.SURVEY_DEFINITION_ID, L.YEAR, L.SPECIES_CODE

UNION ALL

/* 2. OTOLITHS COLLECTED */
SELECT S.SURVEY_DEFINITION_ID, S.YEAR, SPECIMEN.SPECIES_CODE, 
    'OTOLITH' AS SPECIMEN_SAMPLE_TYPE,  
    COUNT(DISTINCT(SPECIMEN.HAULJOIN)) AS N_HAUL, 
    COUNT(*) AS N_SPECIMEN
FROM RACEBASE.SPECIMEN SPECIMEN
JOIN RACEBASE.HAUL H ON H.HAULJOIN = SPECIMEN.HAULJOIN
JOIN RACE_DATA.CRUISES C ON C.RACEBASE_CRUISEJOIN = SPECIMEN.CRUISEJOIN
JOIN RACE_DATA.SURVEYS S ON S.SURVEY_ID = C.SURVEY_ID
WHERE H.ABUNDANCE_HAUL = 'Y'
GROUP BY S.SURVEY_DEFINITION_ID, S.YEAR, SPECIMEN.SPECIES_CODE

UNION ALL

/* 3. AGES READ */
SELECT S.SURVEY_DEFINITION_ID, S.YEAR, SPECIMEN.SPECIES_CODE, 
    'AGE' AS SPECIMEN_SAMPLE_TYPE,     
    COUNT(DISTINCT(SPECIMEN.HAULJOIN)) AS N_HAUL, 
    COUNT(SPECIMEN.AGE) AS N_SPECIMEN
FROM RACEBASE.SPECIMEN SPECIMEN
JOIN RACEBASE.HAUL H ON H.HAULJOIN = SPECIMEN.HAULJOIN
JOIN RACE_DATA.CRUISES C ON C.RACEBASE_CRUISEJOIN = SPECIMEN.CRUISEJOIN
JOIN RACE_DATA.SURVEYS S ON S.SURVEY_ID = C.SURVEY_ID
WHERE H.ABUNDANCE_HAUL = 'Y'
AND AGE IS NOT NULL
GROUP BY S.SURVEY_DEFINITION_ID, S.YEAR, SPECIMEN.SPECIES_CODE;

GRANT SELECT ON SPECIMEN_COUNT TO PUBLIC;
