-- SQL Command to Create Materialized View GAP_PRODUCTS.SPECIMEN
--
-- Created by querying records from RACEBASE.SPECIMEN but only using hauls 
-- with ABUNDANCE_HAUL = 'Y' from the five survey areas w/ survey_definition_id:
-- "AI" = 52, "GOA" = 47, "EBS" = 98, "BSS" = 78, "NBS" = 143
--
-- Contributors: Ned Laman (ned.laman@noaa.gov), 
--               Zack Oyafuso (zack.oyafuso@noaa.gov), 
--               Emily Markowitz (emily.markowitz@noaa.gov)
--

-- SQL Command to Create Materilized View GAP_PRODUCTS.AKFIN_SPECIMEN
--
-- Created by querying records from RACEBASE.SPECIMEN but only using hauls 
-- with ABUNDANCE_HAUL = 'Y' from the five survey areas w/ survey_definition_id:
-- "AI" = 52, "GOA" = 47, "EBS" = 98, "BSS" = 78, "NBS" = 143
--
-- Contributors: Ned Laman (ned.laman@noaa.gov), 
--               Zack Oyafuso (zack.oyafuso@noaa.gov), 
--               Emily Markowitz (emily.markowitz@noaa.gov)
--

CREATE MATERIALIZED VIEW GAP_PRODUCTS.SPECIMEN AS
-- Part 1: Length Frequency Data
SELECT 
    ABS(B.HAUL_ID) AS HAULJOIN,
    -- If year is <= the threshold, use the previous code, otherwise use current
    CASE 
        WHEN S.YEAR <= M.YEAR_STARTED THEN M.SPECIES_CODE_PREV 
        ELSE C.SPECIES_CODE 
    END AS SPECIES_CODE,
    C.SEX,
    SUM(C.FREQUENCY) AS FREQUENCY,
    C.EDIT_LENGTH AS LENGTH_MM,
    C.LENGTH_TYPE,
    C.LENGTH_SUBSAMPLE_TYPE AS SAMPLE_TYPE,
    NULL AS WEIGHT_G,
    NULL AS AGE,
    NULL AS MATURITY,
    NULL AS GONAD_G,
    NULL AS SPECIMEN_SUBSAMPLE_METHOD,
    NULL AS AGE_DETERMINATION_METHOD
FROM RACE_DATA.CRUISES A
JOIN RACE_DATA.SURVEYS S ON (S.SURVEY_ID = A.SURVEY_ID)
JOIN RACE_DATA.SURVEY_DEFINITIONS SD ON (SD.SURVEY_DEFINITION_ID = S.SURVEY_DEFINITION_ID)
JOIN RACE_DATA.HAULS B ON (B.CRUISE_ID = A.CRUISE_ID)
JOIN RACE_DATA.LENGTHS C ON (C.HAUL_ID = B.HAUL_ID)
-- Join to your existing mapping table
LEFT JOIN GAP_PRODUCTS.SPECIES_YEAR M ON C.SPECIES_CODE = M.SPECIES_CODE
GROUP BY 
    B.HAUL_ID, 
    CASE 
        WHEN S.YEAR <= M.YEAR_STARTED THEN M.SPECIES_CODE_PREV 
        ELSE C.SPECIES_CODE 
    END,
    C.SEX, C.EDIT_LENGTH, C.LENGTH_TYPE, C.LENGTH_SUBSAMPLE_TYPE

UNION ALL

-- Part 2: Specimen Data
SELECT 
    ss.HAULJOIN,
    CASE 
        WHEN FLOOR(hh.CRUISE / 100) <= M.YEAR_STARTED THEN M.SPECIES_CODE_PREV 
        ELSE ss.SPECIES_CODE 
    END AS SPECIES_CODE,
    ss.SEX,
    NULL AS FREQUENCY,
    ss.LENGTH AS LENGTH_MM,
    NULL AS LENGTH_TYPE,
    ss.SPECIMEN_SAMPLE_TYPE AS SAMPLE_TYPE,
    ss.WEIGHT WEIGHT_G,
    ss.AGE,
    ss.MATURITY,
    ss.GONAD_WT AS GONAD_G,
    ss.SPECIMEN_SUBSAMPLE_METHOD,
    ss.AGE_DETERMINATION_METHOD
FROM RACEBASE.SPECIMEN ss
JOIN RACEBASE.HAUL hh 
ON ss.HAULJOIN = hh.HAULJOIN
LEFT JOIN GAP_PRODUCTS.SPECIES_YEAR M 
ON ss.SPECIES_CODE = M.SPECIES_CODE
WHERE hh.ABUNDANCE_HAUL = 'Y'


-- Code for GAP_PRODUCTS.SPECIMEN for posterity 2026-05-12

-- CREATE MATERIALIZED VIEW GAP_PRODUCTS.SPECIMEN AS
-- SELECT 
--     h.HAULJOIN,
--     s.SPECIMENID                 AS SPECIMEN_ID,
--     s.SPECIES_CODE,
--     s.LENGTH                     AS LENGTH_MM,
--     s.SEX,
--     s.WEIGHT                     AS WEIGHT_G,
--     s.AGE,
--     s.MATURITY,
--     s.GONAD_WT                   AS GONAD_G,
--     s.SPECIMEN_SUBSAMPLE_METHOD,
--     s.SPECIMEN_SAMPLE_TYPE,
--     s.AGE_DETERMINATION_METHOD 
-- FROM RACEBASE.SPECIMEN s
-- JOIN RACEBASE.HAUL h 
--     ON h.HAULJOIN = s.HAULJOIN
-- JOIN RACE_DATA.CRUISES c 
--     ON c.RACEBASE_CRUISEJOIN = h.CRUISEJOIN
-- JOIN RACE_DATA.SURVEYS surv 
--     USING (SURVEY_ID)
-- WHERE h.ABUNDANCE_HAUL = 'Y'
--   AND surv.SURVEY_DEFINITION_ID IN (143, 98, 47, 52, 78);
  
-- Original code for GAP_PRODUCTS.AKFIN_SPECIMEN for posterity 2026-05-10
  
-- CREATE MATERIALIZED VIEW GAP_PRODUCTS.AKFIN_SPECIMEN AS 
-- SELECT HAULJOIN, SPECIMENID AS SPECIMEN_ID, SPECIES_CODE, LENGTH AS LENGTH_MM, 
-- SEX, WEIGHT AS WEIGHT_G, AGE, MATURITY, GONAD_WT AS GONAD_G, 
-- SPECIMEN_SUBSAMPLE_METHOD, SPECIMEN_SAMPLE_TYPE, AGE_DETERMINATION_METHOD 
-- 
-- FROM RACEBASE.SPECIMEN 
-- JOIN RACEBASE.HAUL USING (HAULJOIN)
-- WHERE RACEBASE.HAUL.ABUNDANCE_HAUL = 'Y'
