-- SAMPLESIZE VIEW: 
-- SUMMARY TABLE OF NUMBER OF HAULS AND INDIVIDUALS WHERE LENGTHS AND OTOLITH
-- WERE COLLECTED 
-- Zack Oyafuso

CREATE OR REPLACE VIEW GAP_PRODUCTS.SAMPLESIZE AS 

-- TABULATE NUMBER OF LENGTHED INDIVIDUALS, JOIN WITH N_LENGTH 
SELECT SURVEY_DEFINITION_ID, YEAR, SPECIES_CODE, 
'LENGTH' AS SPECIMEN_SAMPLE_TYPES, 
N_LENGTH AS N_SAMPLE, SUM(FREQUENCY) COUNT_VALUE
FROM GAP_PRODUCTS.AKFIN_LENGTH
JOIN (SELECT CRUISEJOIN, HAULJOIN FROM AKFIN_HAUL) 
USING (HAULJOIN)
JOIN (SELECT CRUISEJOIN, YEAR, SURVEY_DEFINITION_ID FROM AKFIN_CRUISE ) 
USING (CRUISEJOIN)
JOIN (SELECT SURVEY_DEFINITION_ID, YEAR, SPECIES_CODE, N_LENGTH 
FROM GAP_PRODUCTS.BIOMASS 
WHERE N_LENGTH > 0  AND YEAR != 2025 -- REMEMBER TO REMOVE
AND AREA_ID IN (99900, 99902, 99903, 99904, 99905) -- EXCLUDE EBS STANDARD AREA
) 
USING (SURVEY_DEFINITION_ID, YEAR, SPECIES_CODE)
GROUP BY SURVEY_DEFINITION_ID, YEAR, SPECIES_CODE, N_LENGTH

UNION
-- TABULATE NUMBER OF OTOLITHS COLLECTED
SELECT SURVEY_DEFINITION_ID, YEAR, SPECIES_CODE,
'OTOLITH' AS SPECIMEN_SAMPLE_TYPES,
COUNT(DISTINCT HAULJOIN) AS N_SAMPLE,
COUNT(*) AS COUNT_VALUE
FROM AKFIN_SPECIMEN 
JOIN (SELECT CRUISEJOIN, HAULJOIN FROM AKFIN_HAUL) USING (HAULJOIN)
JOIN (SELECT CRUISEJOIN, YEAR, SURVEY_DEFINITION_ID FROM AKFIN_CRUISE) USING (CRUISEJOIN)
GROUP BY SPECIES_CODE, SURVEY_DEFINITION_ID, YEAR

UNION
-- TABULATE NUMBER OF OTOLITHS COLLECTED
SELECT SURVEY_DEFINITION_ID, YEAR, SPECIES_CODE,
'AGE' AS SPECIMEN_SAMPLE_TYPES,
COUNT(DISTINCT HAULJOIN) AS N_SAMPLE,
COUNT(*) AS COUNT_VALUE
FROM AKFIN_SPECIMEN 
JOIN (SELECT CRUISEJOIN, HAULJOIN FROM AKFIN_HAUL) USING (HAULJOIN)
JOIN (SELECT CRUISEJOIN, YEAR, SURVEY_DEFINITION_ID FROM AKFIN_CRUISE) USING (CRUISEJOIN)
WHERE AGE IS NOT NULL
GROUP BY SPECIES_CODE, SURVEY_DEFINITION_ID, YEAR

ORDER BY YEAR, SURVEY_DEFINITION_ID, SPECIES_CODE;
