---
title: Access API data using R
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE, echo = TRUE)
```

Use the below function to pull AKFIN data through AKFIN's API.

```{r akfin-api-fn}
# load libraries
library(dplyr)
library(magrittr)
library(httr)
library(flextable)

# tell R to not use scientific notation
options(scipen=999)

# function for pulling data from the api using the httr package
get_gap_biomass<-function(area_id, species_code) {
  # paste(... collapse=",") puts commas between vector elements
  area_id <- paste(area_id, collapse = ",")
  species_code <- paste(species_code, collapse = ",")
  # httr code, parameters are after the '?'
  httr::content(
    httr::GET(paste0("https://apex.psmfc.org/akfin/data_marts/akmp/gap_biomass?area_id=",
                     area_id,
                     "&species_code=",
                     species_code)),
    type = "application/json") %>%
    # convert to data frame
    bind_rows()
}
```

## Ex. 1: Load lingcod data

```{r}
#| label: test-1
#| tbl-cap: "Ex. 1: Load lingcod data. "
#| eval: false

lincod_biomass<-get_gap_biomass(area_id=c(40, 41), species_code=21910)
flextable::flextable(head(lincod_biomass))
```
