---
title: Data Products & Tools
---

```{r setup, include=FALSE}
#| file: functions.R
```

To accompany these data, we also produce data products to make using our data more accessible and straightforward.

```{r, echo = FALSE, include = FALSE}
library(googledrive)
library(magrittr)
library(flextable)
googledrive::drive_auth()
2

# PLEASE UPDATE THIS GOOGLE DRIVE TO UPDATE CONTENT
googledrive::drive_download(
  file = googledrive::as_id("1fBNElCcrLTWkSAbjEoShsduuyMfHEisJDyyumCpCSAw"), #1FJe2kqkcKpgOh4YS1_QJqaPX2wvOdhGu0DkPBF-SsQs
  type = "csv",
  overwrite = TRUE,
  path = here::here("content", "other_products.csv"))
```

```{r prod-table}
#| tbl-cap: Survey of products developed by GAP
#| message: false
#| warning: false
#| echo: false

table_raw <- read.csv(file = here::here("content", "other_products.csv"), 
                      skip = 1)  %>% 
  dplyr::mutate(
    poc_goa = gsub(x = poc_goa, 
                      pattern = " & ", replacement = " &\n"), 
    poc_ai = gsub(x = poc_ai, 
                      pattern = " & ", replacement = " &\n"), 
    poc_bs = gsub(x = poc_bs, 
                  pattern = " & ", replacement = " &\n"), 
    include = ifelse(is.na(include), TRUE, include), 
    product_type = stringr::str_to_title(product_type), 
    product_type  = factor(x = product_type, 
                           levels = c("Data", "Analysis", "Visualization Tools", "Communication"), 
                           labels = c("Data", "Analysis", "Visualization Tools", "Communication"),
                           ordered = TRUE)) %>% 
  dplyr::arrange(product_type) %>% 
  dplyr::filter(include) %>% 
  dplyr::select(-include)

table_raw[is.na(table_raw)] <- "-"

table_print <- 
  flextable::as_grouped_data(x = table_raw, 
                             groups = "product_type", 
                             columns = NULL) %>% 
  flextable::as_flextable(
    col_keys = c(#"product_type", 
      "product",
      "poc_ai", "poc_goa", "poc_bs", "description")) %>% 
  flextable::compose(j = "product",
                     value = as_paragraph(flextable::hyperlink_text(
                       x = product, url = link ) ) )  %>% 
  flextable::compose(
    i = ~ !is.na(product_type),
    j = "product",
    value = as_paragraph(as_chunk(product_type))) %>%
  flextable::theme_zebra()  %>% 
  flextable::set_header_labels(
    product = "Product", 
    poc_goa = "Point of Contact\nGOA", 
    poc_ai = "Point of Contact\nAI", 
    poc_bs = "Point of Contact\nBS", 
    description = "Description") %>% 
  flextable::merge_h() %>% 
  flextable::padding(padding = 5, part = "all") %>%
  flextable::color(j = "product", i = ~ is.na(product_type), 
                   color = "darkblue", part = "body") %>% 
  flextable::bg(i = ~ !is.na(product_type), bg = "grey70") %>% 
  flextable::bold(i = ~ is.na(product_type), bold = TRUE, j = "product") %>%
  flextable::italic(i = ~ !is.na(product_type), italic = TRUE) %>% 
  flextable::padding(padding.left = 10, 
                     j = "product", 
                     i = ~ !is.na(product_type), 
                     part = "body") %>% 
  flextable::padding(padding.left = 15, 
                     j = "product", 
                     i = ~ is.na(product_type), 
                     part = "body") %>% 
  flextable::width(width = c(2,1.5,1.5,1.5,3))

table_print
```
