---
title: Outreach
---

## Real-time temperatures and survey progress

Maps of [near real-time temperatures and survey progress from each of our bottom trawl surveys](https://www.fisheries.noaa.gov/alaska/science-data/bottom-trawl-survey-temperature-maps) are posted each business day of the survey. Water temperature affects many species' spawning times, access to food, growth rates, and overall range. Collecting temperature data helps better understand species’ habitats and the larger ecosystem. 

**POCs:** Bering Sea: Emily Markowitz, Liz Dawson, Chris Anderson

### Community Highlights

```{r}
a <- ""
bibfiletext <- readLines(con = "https://raw.githubusercontent.com/afsc-gap-products/citations/main/cite/bibliography.bib")
aa<-which(grepl(pattern = "NBSCommunity", x = bibfiletext))
ref <- bibfiletext[aa]
ref <- sapply(strsplit(x = ref, split = "{", fixed = TRUE), "[[", 2)
ref <- gsub(x = ref, pattern = ",", replacement = "", fixed = TRUE)
temp <- as.numeric(gsub(pattern = "[A-Za-z]+", replacement = "", x = ref))
ref <- ref[which(temp == max(temp))]
```

Each year, the Groundfish Assessment Program compiles it’s survey findings for communities around Alaska [@`r paste0(ref)`]. *Please note: This document is for informational purposes only and does not necessarily represent the views or official position of the Department of Commerce, the National Oceanic and Atmospheric Administration, or the National Marine Fisheries Service. Not to be cited without permission from the authors. *

**POCs:** Bering Sea: Emily Markowitz, Liz Dawson, Chris Anderson