-- Mirror of GAP_PRODUCTS.TAXONOMIC_CLASSIFICATION
-- Subsetting for SURVEY_SPECIES = 1 includes taxonomic classifications
-- accepted by the AFSC GAP bottom trawl survey
SELECT 
  SPECIES_NAME, 
  COMMON_NAME, 
  SPECIES_CODE, 
  ID_RANK, 
  DATABASE_ID, 
  DATABASE, 
  GENUS_TAXON, 
  SUBFAMILY_TAXON, 
  FAMILY_TAXON, 
  SUPERFAMILY_TAXON, 
  SUBORDER_TAXON, 
  ORDER_TAXON, 
  SUPERORDER_TAXON, 
  SUBCLASS_TAXON, 
  CLASS_TAXON, 
  SUPERCLASS_TAXON, 
  SUBPHYLUM_TAXON, 
  PHYLUM_TAXON, 
  KINGDOM_TAXON,
  TRUNC(SYSDATE) AKFIN_LOAD_DATE

FROM GAP_PRODUCTS.TAXONOMIC_CLASSIFICATION
WHERE SURVEY_SPECIES = 1
