-- Non-zero catch records from hauls in RACEBASE.HAUL where ABUNDANCE_HAUL = 'Y'
SELECT CRUISEJOIN, HAULJOIN, CATCHJOIN, SPECIES_CODE, 
       WEIGHT WEIGHT_KG, NUMBER_FISH COUNT, TRUNC(SYSDATE) AKFIN_LOAD_DATE
FROM   RACEBASE.CATCH
JOIN   RACEBASE.HAUL USING (CRUISEJOIN, HAULJOIN)
WHERE  RACEBASE.HAUL.ABUNDANCE_HAUL = 'Y';
