-- SQL Command to Create Materilized View GAP_PRODUCTS.AKFIN_CRUISE
--
-- Note: the five survey areas w/ survey_definition_id:
-- "AI" = 52, "GOA" = 47, "EBS" = 98, "BSS" = 78, "NBS" = 143
--
-- Contributors: Ned Laman (ned.laman@noaa.gov), 
--               Zack Oyafuso (zack.oyafuso@noaa.gov), 
--               Emily Markowitz (emily.markowitz@noaa.gov)
--

CREATE MATERIALIZED VIEW GAP_PRODUCTS.AKFIN_CRUISE AS

SELECT DISTINCT 
A.CRUISEJOIN, 
B.CRUISE, 
FLOOR(B.CRUISE/100) YEAR, 
D.SURVEY_DEFINITION_ID, 
D.SURVEY_NAME, 
B.VESSEL_ID, 
E.NAME VESSEL_NAME,
F.ACRONYM SPONSOR_ACRONYM, 
C.START_DATE DATE_START, 
C.END_DATE DATE_END
FROM RACEBASE.HAUL A, 
RACE_DATA.CRUISES B, 
RACE_DATA.SURVEYS C, 
RACE_DATA.SURVEY_DEFINITIONS D, 
RACE_DATA.VESSELS E, 
RACE_DATA.ORGANIZATIONS F
WHERE A.VESSEL = B.VESSEL_ID
AND B.VESSEL_ID = E.VESSEL_ID
AND A.CRUISE = B.CRUISE 
AND C.SURVEY_ID =  B.SURVEY_ID 
AND C.SURVEY_DEFINITION_ID = D.SURVEY_DEFINITION_ID 
AND D.SURVEY_DEFINITION_ID IN (143,98,47,52,78)
AND A.ABUNDANCE_HAUL = 'Y'
AND F.ORGANIZATION_ID = C.SPONSOR_ORGANIZATION_ID
