-- SQL Command to Create Materilized View GAP_PRODUCTS.AKFIN_SPECIMEN
--
-- Created by querying records from RACEBASE.SPECIMEN but only using hauls 
-- with ABUNDANCE_HAUL = 'Y' from the five survey areas w/ survey_definition_id:
-- "AI" = 52, "GOA" = 47, "EBS" = 98, "BSS" = 78, "NBS" = 143
--
-- Contributors: Ned Laman (ned.laman@noaa.gov), 
--               Zack Oyafuso (zack.oyafuso@noaa.gov), 
--               Emily Markowitz (emily.markowitz@noaa.gov)
--


-- old code
-- CREATE MATERIALIZED VIEW GAP_PRODUCTS.AKFIN_SPECIMEN AS 
-- SELECT HAULJOIN, SPECIMENID AS SPECIMEN_ID, SPECIES_CODE, LENGTH AS LENGTH_MM, 
-- SEX, WEIGHT AS WEIGHT_G, AGE, MATURITY, GONAD_WT AS GONAD_G, 
-- SPECIMEN_SUBSAMPLE_METHOD, SPECIMEN_SAMPLE_TYPE, AGE_DETERMINATION_METHOD 
-- 
-- FROM RACEBASE.SPECIMEN 
-- JOIN RACEBASE.HAUL USING (HAULJOIN)
-- WHERE RACEBASE.HAUL.ABUNDANCE_HAUL = 'Y'

-- new code with crabs and length_type

/* --- PART 1: FISH SPECIMENS --- */
SELECT 
    S.HAULJOIN, 
    S.SPECIMENID AS SPECIMEN_ID, 
    S.SPECIES_CODE, 
    S.LENGTH AS LENGTH_MM, 
    L.LENGTH_TYPE, -- Sourced from AKFIN_LENGTH
    S.SEX, 
    S.WEIGHT AS WEIGHT_G, 
    S.AGE, 
    S.MATURITY, 
    S.GONAD_WT AS GONAD_G, 
    S.SPECIMEN_SUBSAMPLE_METHOD, 
    S.SPECIMEN_SAMPLE_TYPE, 
    S.AGE_DETERMINATION_METHOD,
    -- Crab-specific columns (set to NULL for Fish)
    NULL AS SHELL_CONDITION,
    NULL AS EGG_CONDITION,
    NULL AS CLUTCH_SIZE,
    NULL AS MERUS_LENGTH,
    NULL AS CHELA_HEIGHT,
    NULL AS DISEASE_CODE,
    NULL AS SAMPLING_FACTOR
FROM RACEBASE.SPECIMEN S
JOIN RACEBASE.HAUL H 
    ON S.HAULJOIN = H.HAULJOIN
-- Join to get the unique LENGTH_TYPE for Fish species
LEFT JOIN (SELECT DISTINCT SPECIES_CODE, LENGTH_TYPE FROM AKFIN_LENGTH) L
    ON S.SPECIES_CODE = L.SPECIES_CODE
WHERE H.ABUNDANCE_HAUL = 'Y'

UNION ALL

/* --- PART 2: CRAB SPECIMENS --- */
SELECT 
    C.HAULJOIN, 
    NULL AS SPECIMEN_ID, -- No numeric ID in CRAB_SPECIMEN
    C.SPECIES_CODE, 
    C.LENGTH_MM, 
    C.LENGTH_TYPE, -- Temporarily hardcoded while testing code --     species_code %in% c(68541, 68550, 68560) ~ 8, TRUE ~ 7
    -- Conditional logic for Crab Length Type
    CASE 
        WHEN C.SPECIES_CODE IN (68541, 68550, 68560) THEN 8 
        ELSE 7 
    END AS LENGTH_TYPE,
    C.SEX, 
    C.WEIGHT_G, 
    -- Fish-specific columns (set to NULL for Crabs)
    NULL AS AGE, 
    NULL AS MATURITY, 
    NULL AS GONAD_G, 
    NULL AS SPECIMEN_SUBSAMPLE_METHOD, 
    NULL AS SPECIMEN_SAMPLE_TYPE, 
    NULL AS AGE_DETERMINATION_METHOD,
    -- Crab-specific columns
    C.SHELL_CONDITION,
    C.EGG_CONDITION,
    C.CLUTCH_SIZE,
    C.MERUS_LENGTH,
    C.CHELA_HEIGHT,
    C.DISEASE_CODE,
    C.SAMPLING_FACTOR
FROM MARKOWITZE.CRAB_SPECIMEN C
JOIN RACEBASE.HAUL H 
    ON C.HAULJOIN = H.HAULJOIN
WHERE H.ABUNDANCE_HAUL = 'Y';

