---
title: '`r ifelse(tocTF, "data", "AFSC RACE Groundfish and Shellfish Survey Public Data")`'
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
  md_document: 
    variant: gfm
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa-no-ampersand.csl"
bibliography: "https://raw.githubusercontent.com/afsc-gap-products/citations/main/cite/bibliography.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE)
```

<!-- README.md is generated from README.Rmd. Please edit that file -->

- [General information](https://afsc-gap-products.github.io/gap_products/)
- [Access production data via the AFSC Oracle Database (AFSC only) using SQL and R](https://afsc-gap-products.github.io/gap_products//access-afsc-oracle-sql-r.html)

## Column Metadata

Here are stock metadata that users can use to document their table columns. `r readtext::readtext(file = here::here(dir_out,"metadata_column_metadata_table.txt"))$text`.

```{r metadata-column, echo = FALSE, eval = TRUE}
metadata_column0 <- read.csv(file = paste0(dir_out, "metadata_column.csv"))  %>% 
  dplyr::arrange(metadata_colname) %>% 
  dplyr::select(
    "Column name from data" = metadata_colname, 
    "Descriptive column Name" = metadata_colname_long, 
    "Units" = metadata_units, 
    "Units" = metadata_units, 
    "Oracle data type" = metadata_datatype, 
    "Column description" = metadata_colname_desc)
knitr::kable(metadata_column0, row.names = FALSE)
# flextable::flextable(metadata_column0)
```

```{r child-footer, child=here::here("docs","footer.Rmd")}
```