---
title: '`r ifelse(tocTF, "data", "AFSC RACE Groundfish and Shellfish Survey Public Data")`'
description: '`r ifelse(tocTF, "data", "AFSC RACE Groundfish and Shellfish Survey Public Data")`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE)
```

## Data created in this repo

```{r oracle-connect-1, echo = FALSE, eval = TRUE}
if (file.exists("Z:/Projects/ConnectToOracle.R")) {
    source("Z:/Projects/ConnectToOracle.R")
    channel <- channel_products
} else {
  gapindex::get_connected()
}
```

```{r table-locations, eval = TRUE, echo = FALSE}
 # You can download all of the tables and saving them locally. These are all of the new tables for you to look through:

locations <- c(
  "GAP_PRODUCTS.CPUE",
  "GAP_PRODUCTS.BIOMASS",
  "GAP_PRODUCTS.AGECOMP",
  "GAP_PRODUCTS.SIZECOMP",
  "GAP_PRODUCTS.STRATUM_GROUPS",
  "GAP_PRODUCTS.AREA",
  "GAP_PRODUCTS.SURVEY_DESIGN",
  "GAP_PRODUCTS.TAXONOMICS_WORMS", 
  "GAP_PRODUCTS.TAXONOMICS_ITIS", 
  "GAP_PRODUCTS.TAXON_CONFIDENCE", 
  "GAP_PRODUCTS.METADATA_COLUMN" 
  )
```

```{r table-dl, eval = FALSE, echo = FALSE}
for (i in 1:length(locations)) {
  print(locations[i])
  a <- RODBC::sqlQuery(channel, paste0("SELECT * FROM ", locations[i]))
  write.csv(x = a, file = here::here("data", paste0(locations[i], ".csv")))
}
```

```{r table-load, eval = TRUE, echo = FALSE}

 # Find all descriptions of all tables in the GAP_PRODUCTS schema
b <- RODBC::sqlQuery(channel = channel, 
                     query = "SELECT table_name, comments 
FROM all_tab_comments 
WHERE owner = 'GAP_PRODUCTS' 
ORDER BY table_name")

 # Collect all column metadata for all tables
str00 <- c()
for (i in 1:length(locations)) {
  metadata_table <- b$COMMENTS[b$TABLE_NAME == 
                                 strsplit(x = locations[i], split = ".", fixed = TRUE)[[1]][2]]
  metadata_table <- ifelse(is.na(metadata_table), 
                           "[There is currently no description for this table.]", 
                           metadata_table)
  
  a <- readr::read_csv(here::here("data", paste0(locations[i], ".csv")))
  
  temp <- file.size(here::here("data", paste0(locations[i], ".csv")))
  temp_rows <- RODBC::sqlQuery(channel = channel, 
                     query = paste0("SELECT COUNT(*) FROM " ,locations[i], ";"))
    temp_cols <- ncol(a)
 #       RODBC::sqlQuery(channel = channel, 
 #                      query = paste0("SELECT COUNT(COLUMN_NAME)
 # FROM INFORMATION_SCHEMA.COLUMNS
 # WHERE TABLE_SCHEMA = 'GAP_PRODUCTS'
 # AND table_name = '" ,gsub(pattern = "GAP_PRODUCTS.", replace = "", x = locations[i]), "';"))
  
  str0 <- paste0("### ", locations[i], "\n\n", 
                 metadata_table, "\n\n",
"rows: ", temp_rows, " | cols: ", temp_cols, " | ", 
formatC(x = temp/ifelse(temp>1e+7, 1e+9, 1), 
           digits = 1, format = "f", big.mark = ","), 
" ", ifelse(temp>1e+7, "GB", "B"), "

\n\n\n")
  
  str00 <- paste0(str00, str0)
  # cat(str0)
  # # what are the metadata for each column of this table
  # flextable::flextable(metadata_column[metadata_column$METADATA_COLNAME %in% names(a),])
  # # print few first lines of this table for show
  # flextable::flextable(head(a, 3))
}
```

`r str00`

