-- CREATE CTD_VARIABLE_CODES

CREATE TABLE CTD_VARIABLE_CODES (
  VARIABLE    NUMBER(3,0) NOT NULL,
  VAR_NAME    VARCHAR2(255 BYTE),
  UNITS       VARCHAR2(255 BYTE),
  DESCRIPTION VARCHAR2(255 BYTE),
  
  CONSTRAINT pk_ctd_variable_codes
    PRIMARY KEY (VARIABLE)  
);
GRANT SELECT ON CTD_VARIABLE_CODES TO PUBLIC;


CREATE TABLE CTD_DIRECTION_CODES (
  DIRECTION   NUMBER(1,0) NOT NULL,
  DESCRIPTION VARCHAR2(255 BYTE),
  
  CONSTRAINT pk_ctd_direction_codes
    PRIMARY KEY (DIRECTION)
);
GRANT SELECT ON CTD_DIRECTION_CODES TO PUBLIC;

CREATE TABLE CTD_INSTRUMENT_CODES (
  INSTRUMENT  NUMBER(3,0) NOT NULL,
  DESCRIPTION VARCHAR2(255 BYTE),
  
  CONSTRAINT pk_ctd_instrument_codes 
    PRIMARY KEY (INSTRUMENT)
);
GRANT SELECT ON CTD_INSTRUMENT_CODES TO PUBLIC;

CREATE TABLE CTD_HAUL_INSTRUMENT (
  HAULJOIN   NUMBER(12,0) NOT NULL, 
  INSTRUMENT NUMBER(3,0)  NOT NULL,
  
  --CONSTRAINT fk_ctd_haul_instrument_hauljoin 
   --FOREIGN KEY (HAULJOIN) REFERENCES RACEBASE.HAUL(HAULJOIN),
    
  CONSTRAINT fk_ctd_haul_instrument_instrument 
    FOREIGN KEY (INSTRUMENT) REFERENCES CTD_INSTRUMENT_CODES(INSTRUMENT)
);
GRANT SELECT ON CTD_HAUL_INSTRUMENT TO PUBLIC;

CREATE TABLE CTD_DATA (
  HAULJOIN   NUMBER(12,0)  NOT NULL, 
  DIRECTION  NUMBER(12,0)  NOT NULL,
  DEPTH_M    NUMBER(5,0)   NOT NULL,
  VARIABLE   NUMBER(3,0)   NOT NULL,
  VALUE      NUMBER(11,6)  NOT NULL, 
  
  -- Foreign Key Constraints
  --CONSTRAINT fk_ctd_data_hauljoin 
    --FOREIGN KEY (HAULJOIN) REFERENCES RACEBASE.HAUL(HAULJOIN), 
    
  CONSTRAINT fk_ctd_data_direction 
    FOREIGN KEY (DIRECTION) REFERENCES CTD_DIRECTION_CODES(DIRECTION),
    
  CONSTRAINT fk_ctd_data_variable 
    FOREIGN KEY (VARIABLE) REFERENCES CTD_VARIABLE_CODES(VARIABLE),
    
  -- Composite Primary Key Constraint
  CONSTRAINT pk_ctd_data 
    PRIMARY KEY (HAULJOIN, DIRECTION, DEPTH_M, VARIABLE)
);
GRANT SELECT ON CTD_DATA TO PUBLIC;







